#!/bin/bash
echo "Starting compilation of gosu 0.151..."
cd ./build
rm -r *.o
make
strip g*
mv g* "/home/edwin/workspace/HiddenChestXP/KScenario Gosu/"
cd "/home/edwin/workspace/HiddenChestXP/KScenario Gosu/"
./play
